import Head from 'next/head'
import Homepage from '@/views/home'
import useNewsStore from '@/zustand/store';




export default function Home() {

  const store = useNewsStore((state) => state);
  console.log(store,`store`);

  return (
    <>
      <Head>
        <title>24*7 news</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage/>
    
        
      
    </>
  )
}
